force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Survey Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Detail_Response__c.field-meta.xml
<CustomField>
    <fullName>Detail_Response__c</fullName>
    <inlineHelpText>Recipient&apos;s response to the request for additional detail.</inlineHelpText>
    <label>Detail Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Follows_Up__c.field-meta.xml
<CustomField>
    <fullName>Follows_Up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If populated, this answer follows up the related one when an item in the question&apos;s &quot;Answers That Request More Info&quot; is selected.</inlineHelpText>
    <label>Follows Up</label>
    <referenceTo>Survey_Answer__c</referenceTo>
    <relationshipLabel>Follow Ups</relationshipLabel>
    <relationshipName>Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <inlineHelpText>Recipient&apos;s response to the prompt.</inlineHelpText>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The question these responses relate to.</inlineHelpText>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Survey Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Answers_That_Request_More_Info__c.field-meta.xml
<CustomField>
    <fullName>Answers_That_Request_More_Info__c</fullName>
    <inlineHelpText>The responses listed here prompt the user for more detail.</inlineHelpText>
    <label>Answers That Request More Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Binary_Label_A__c.field-meta.xml
<CustomField>
    <fullName>Binary_Label_A__c</fullName>
    <defaultValue>&quot;Yes&quot;</defaultValue>
    <label>Binary Label A</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Binary_Label_B__c.field-meta.xml
<CustomField>
    <fullName>Binary_Label_B__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Binary Label B</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Follows_Up__c.field-meta.xml
<CustomField>
    <fullName>Follows_Up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If populated, this question follows up the related one when an item in &quot;Answers That Request More Info&quot; is selected.</inlineHelpText>
    <label>Follows Up</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Follow Ups</relationshipLabel>
    <relationshipName>Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/More_Info_Prompt__c.field-meta.xml
<CustomField>
    <fullName>More_Info_Prompt__c</fullName>
    <inlineHelpText>The text to display when the system requests the user to provide more information.</inlineHelpText>
    <label>More Info Prompt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Picklist_Options__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Options__c</fullName>
    <label>Picklist Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <inlineHelpText>The question or prompt you wish to display.</inlineHelpText>
    <label>Prompt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <inlineHelpText>What type of question is this? Visit the following URL to view explanation of options.
https://x3st-surveys-developer-edition.na78.force.com/docs</inlineHelpText>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Long Form</fullName>
            </value>
            <value>
                <fullName>Short Form</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Multi-Select</fullName>
            </value>
            <value>
                <fullName>Binary</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Color</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Password</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Range_Maximum__c.field-meta.xml
<CustomField>
    <fullName>Range_Maximum__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>The maximum option available for a Range Type Question.</inlineHelpText>
    <label>Range Maximum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Range_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Range_Minimum__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>The minimum option available for a Range Type Question.</inlineHelpText>
    <label>Range Minimum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Range_Step__c.field-meta.xml
<CustomField>
    <fullName>Range_Step__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>The increment between options in a Range Type Question</inlineHelpText>
    <label>Range Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/Survey_Question_Assignment__c.object-meta.xml
<CustomObject>
    <label>Survey Question Assignment</label>
    <nameField>
        <displayFormat>SQA-{000000}</displayFormat>
        <label>Survey Question Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <formula>TEXT(Survey_Question__r.Question_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Require_More_Detail__c.field-meta.xml
<CustomField>
    <fullName>Require_More_Detail__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Require the survey recipient to provide additional detail if and when prompted.</inlineHelpText>
    <label>Require More Detail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Require_Response__c.field-meta.xml
<CustomField>
    <fullName>Require_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Require the survey recipient to answer the question.</inlineHelpText>
    <label>Require Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Assignments</relationshipLabel>
    <relationshipName>Survey_Question_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/When_To_Display__c.field-meta.xml
<CustomField>
    <fullName>When_To_Display__c</fullName>
    <defaultValue>&quot;Always&quot;</defaultValue>
    <label>When To Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
            </value>
            <value>
                <fullName>For Positive Feedback</fullName>
            </value>
            <value>
                <fullName>For Neutral Feedback</fullName>
            </value>
            <value>
                <fullName>For Negative Feedback</fullName>
            </value>
            <value>
                <fullName>For Positive or Negative Feedback</fullName>
            </value>
            <value>
                <fullName>For Positive or Neutral Feedback</fullName>
            </value>
            <value>
                <fullName>For Negative or Neutral Feedback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SurveyEntry.cls
public class SurveyEntry
{
    public Survey_Question__c question {get; set;}
    public Survey_Question_Assignment__c assignment {get; set;}
    public Survey_Answer__c answer {get; set;}
    
    public string prompt {
        get
        {
            return question.Prompt__c;
        }
    }
    public string detailprompt {
        get
        {
            return question.More_Info_Prompt__c;
        }
    }
    public string type {
        get
        {
            return question.Question_Type__c;
        }
    }
    public List<string> options {
        get
        {
           List<string> retval = new List<string>();
           if (question.Picklist_Options__c != null)
           {
               retval = question.Picklist_Options__c.split('\\n');
           }
           for (integer ndx = 0; ndx < retval.size(); ndx++)
           {
               retval.set(ndx, retval.get(ndx).trim());
           }
           return retval;
        }
    }
    public string answers_request_detail {
        get
        {
            return question.Answers_That_Request_More_Info__c;
        }
    }
    public string first_label {
        get
        {
            return question.Binary_Label_A__c;
        }
    }
    public string second_label {
        get
        {
            return question.Binary_Label_B__c;
        }
    }
    public decimal min_value {
        get
        {
            return (question.Range_Minimum__c == null ? 1 : question.Range_Minimum__c);
        }
    }
    public decimal max_value {
        get
        {
            return (question.Range_Maximum__c == null ? 10 : question.Range_Maximum__c);
        }
    }
    public decimal step {
        get
        {
            return (question.Range_Step__c == null ? 1 : question.Range_Step__c);
        }
    }
    public list<decimal> values {
        get
        {
            List<decimal> retval = new List<decimal>();
            decimal ndx = min_value;
            while (ndx <= max_value)
            {
                retval.add(ndx);
                ndx += step;
            }
            return retval;
        }
    }
    public boolean require_response {
        get
        {
            return (assignment == null ? null : assignment.Require_Response__c);
        }
    }
    public boolean require_detailresponse {
        get
        {
            return (assignment == null ? null : assignment.Require_More_Detail__c);
        }
    }
    public string display {
        get
        {
            return (assignment == null ? null : assignment.When_To_Display__c);
        }
    }
    public List<string> responses {
        get
        {
            return (answer.Response__c == null ? new List<string>{''} : answer.Response__c.split(';'));
        }
    }
    public boolean hasResponse(string resp) {
        return responses.contains(resp);
    }
    public string response {
        get
        {
            return answer.Response__c;
        }
    }
    public string detailresponse {
        get
        {
            return answer.Detail_Response__c;
        }
    }
    
    private List<SurveyEntry> pvt_followups = new List<SurveyEntry>();
    public List<SurveyEntry> followups {
        get
        {
            return pvt_followups;
        }
    }
    
    public SurveyEntry() { }
    public SurveyEntry(Survey_Question__c q, Survey_Question_Assignment__c qa, Survey_Answer__c a)
    {
        this.question = q;
        this.assignment = qa;
        this.answer = a;
        
        for (Survey_Answer__c fa : a.Follow_Ups__r)
        {
            for (Survey_Question__c fq : q.Follow_Ups__r)
            {
                if (fq.Id == fa.Survey_Question__c) {
                    this.pvt_followups.add(new SurveyEntry(fq, null, fa));
                    break;
                }
            }
        }
    }
}