force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Survey Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Detail_Response__c.field-meta.xml
<CustomField>
    <fullName>Detail_Response__c</fullName>
    <inlineHelpText>Recipient&apos;s response to the request for additional detail.</inlineHelpText>
    <label>Detail Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Follows_Up__c.field-meta.xml
<CustomField>
    <fullName>Follows_Up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If populated, this answer follows up the related one when an item in the question&apos;s &quot;Answers That Request More Info&quot; is selected.</inlineHelpText>
    <label>Follows Up</label>
    <referenceTo>Survey_Answer__c</referenceTo>
    <relationshipLabel>Follow Ups</relationshipLabel>
    <relationshipName>Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Question_Detail_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Question_Detail_Prompt__c</fullName>
    <formula>Survey_Question__r.More_Info_Prompt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question Detail Prompt</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Question_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Question_Prompt__c</fullName>
    <formula>Survey_Question__r.Prompt__c</formula>
    <label>Question Prompt</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <inlineHelpText>Recipient&apos;s response to the prompt.</inlineHelpText>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The question these responses relate to.</inlineHelpText>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <label>Survey Response</label>
    <referenceTo>Survey_Response__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Survey Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Follows_Up__c.field-meta.xml
<CustomField>
    <fullName>Follows_Up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If populated, this question follows up the related one when an item in &quot;Answers That Request More Info&quot; is selected.</inlineHelpText>
    <label>Follows Up</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Follow Ups</relationshipLabel>
    <relationshipName>Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Followup_Order__c.field-meta.xml
<CustomField>
    <fullName>Followup_Order__c</fullName>
    <inlineHelpText>Determines the order the follow-ups appear in. Does not do anything for non-followup questions.</inlineHelpText>
    <label>Followup Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/Survey_Question_Assignment__c.object-meta.xml
<CustomObject>
    <label>Survey Question Assignment</label>
    <nameField>
        <displayFormat>SQA-{000000}</displayFormat>
        <label>Survey Question Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Identifies the order the questions are displayed in the survey. If left blank the questions are displayed in the order they were created.</inlineHelpText>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Question_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Question_Prompt__c</fullName>
    <formula>Survey_Question__r.Prompt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question Prompt</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Question_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Assignment__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Assignments</relationshipLabel>
    <relationshipName>Survey_Question_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If the Survey Response is case-specific then this is said case - otherwise this is blank (e.g. for non-support related surveys).</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Collated_Responses__c.field-meta.xml
<CustomField>
    <fullName>Collated_Responses__c</fullName>
    <inlineHelpText>Easy to read view of Responses.</inlineHelpText>
    <label>Collated Responses</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/CSAT__c.field-meta.xml
<CustomField>
    <fullName>CSAT__c</fullName>
    <defaultValue>&quot;Neutral&quot;</defaultValue>
    <label>CSAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Downgrade_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Downgrade_Explanation__c</fullName>
    <inlineHelpText>The response the respondent gave to the &quot;Downgrade Explanation Prompt&quot; (only available &quot;Downgrade Explanation Required&quot; on Survey).</inlineHelpText>
    <label>Downgrade Explanation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Has_Detailed_Responses__c.field-meta.xml
<CustomField>
    <fullName>Has_Detailed_Responses__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked when a survey submission has at least one Answer with specific feedback.</inlineHelpText>
    <label>Has Detailed Response(s)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The survey this response applies to.</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Upgrade_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Upgrade_Explanation__c</fullName>
    <inlineHelpText>The response the respondent gave to the &quot;Upgrade Explanation Prompt&quot; (only available &quot;Upgrade Explanation Required&quot; on Survey).</inlineHelpText>
    <label>Upgrade Explanation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SurveyResponseHandler.cls
public without sharing class SurveyResponseHandler {
    public static Boolean IsTriggerActive = true;
    public enum TriggerOperation {IS_INSERT, IS_UPDATE, IS_DELETE}
    @testVisible
    private Map<Id, Survey_Response__c> oldMap {get; set;}
    private Map<Id, Survey_Response__c> newMap {get; set;}
    private List<Survey_Response__c> oldList {get; set;}
    private List<Survey_Response__c> newList {get; set;}
    private TriggerOperation operation {get; set;}
    private Map<Id, Case> ParentCases;
    
    private List<Survey_Question_Assignment__c> ParentSurveyQuestionAssignments;
    private List<Survey_Answer__c> ChildAnswers;
    private List<Survey_Answer__c> ChildAnswersOrdered;
    private List<Survey_Response__c> ResponsesToUpdate;
    
    public boolean runFromAnswers = false;
    
    public SurveyResponseHandler (Map<Id, Survey_Response__c> oldMap, Map<Id, Survey_Response__c> newMap,
                                      List<Survey_Response__c> oldList, List<Survey_Response__c> newList)
    {
        this.oldMap = oldMap;
        this.newMap = newMap;
        this.oldList = oldList;
        this.newList = newList;
        
        if (oldList == null) {
            this.operation = TriggerOperation.IS_INSERT;
        }
        else {
            this.operation = TriggerOperation.IS_UPDATE;
        }
        
        ResponsesToUpdate = new List<Survey_Response__c>();
    }
    
    public void bulkAfter() {
        if (this.operation == TriggerOperation.IS_DELETE) {
            return;
        }
        
        Set<Id> case_ids = new Set<Id>();
        Set<Id> survey_response_ids = new Set<Id>();
        Set<Id> survey_ids = new Set<Id>();
        
        for (Survey_Response__c sr : newList) {
            if(sr.Case__c != null) {
                case_ids.add(sr.Case__c);
            }
            survey_response_ids.add(sr.Id);
            survey_ids.add(sr.Survey__c);
        }
        
        if (case_ids.size() > 0) {
            ParentCases = new Map<Id, Case>([SELECT Id, AccountId, CSAT_Survey_Response__c
                                                  , CSAT__c, Has_Detailed_CSAT__c
                                               FROM Case
                                              WHERE Id IN: case_ids
                                            ]);
        }
        
        ParentSurveyQuestionAssignments = [SELECT Id, Survey__c, Order__c, Survey_Question__c
                                             FROM Survey_Question_Assignment__c
                                            WHERE Survey__c in :survey_ids
                                            ORDER BY Order__c
                                          ];
        
        ChildAnswers = [SELECT Id, Response__c, Detail_Response__c, Question_Prompt__c, Question_Detail_Prompt__c
                             , Survey_Response__c, Survey_Question__c, Survey_Response__r.Case__c
                             , (SELECT Id, Response__c, Detail_Response__c, Question_Prompt__c, Question_Detail_Prompt__c
                                     , Survey_Response__c, Survey_Question__c, Survey_Response__r.Case__c
                                  FROM Follow_Ups__r
                                 ORDER BY Survey_Question__r.Followup_Order__c
                               )
                          FROM Survey_Answer__c
                         WHERE Survey_Response__c in :survey_response_ids
                       ];
        
        ChildAnswersOrdered = new List<Survey_Answer__c>();
        for (Survey_Question_Assignment__c sqa : ParentSurveyQuestionAssignments)
        {
            for (Survey_Response__c sr : newList)
            {
                for (Survey_Answer__c sa : ChildAnswers)
                {
                    if (sr.Id == sa.Survey_Response__c && sa.Survey_Question__c == sqa.Survey_Question__c)
                    {
                        ChildAnswersOrdered.add(sa);
                    }
                }
            }
        }
    }
    
    public void afterInsert(Survey_Response__c so) {
        collateToParent(so);
    }
    
    public void afterUpdate(Survey_Response__c oldSo, Survey_Response__c so) {
        collateToParent(so);
    }
    
    public void postProcessing() {
        if (ParentCases != null) {
            update ParentCases.values();
        }
    }
    
    private void collateToParent(Survey_Response__c so) {
        
        string collatedResponse = '';
        
        collatedResponse += 
              '<b>' + so.CSAT__c + ' CSAT Left on ' 
            + so.CreatedDate.format('MM/dd/yyyy hh:mm aaa z')
            + '</b><br>'
            + ( so.Downgrade_Explanation__c != null && so.Downgrade_Explanation__c != ''
              ? '<div style="margin-left: 40px;"><b>Downgrade Explanation</b></div>'
              + '<div style="margin-left: 80px;">' + so.Downgrade_Explanation__c + '</b></div>'
              : ''
              )
            + ( so.Upgrade_Explanation__c != null && so.Upgrade_Explanation__c != ''
              ? '<div style="margin-left: 40px;"><b>Upgrade Explanation</b></div>'
              + '<div style="margin-left: 80px;">' + so.Upgrade_Explanation__c + '</b></div>'
              : ''
              )
            ;
        for (Survey_Answer__c sa : ChildAnswersOrdered) {
            if (sa.Survey_Response__c == so.Id)
            {
                collatedResponse += getAnswerCollation(sa, 1);
                
                for (Survey_Answer__c fu : sa.Follow_Ups__r) {
                    collatedResponse += getAnswerCollation(fu, 3);
                }
            }
        }
        
        if (!runFromAnswers && ParentCases != null) {
            Case parent_case = ParentCases.get(so.Case__c);
            
            if (parent_case == null) {
                return;
            }
    
            parent_case.Has_Detailed_CSAT__c = so.Has_Detailed_Responses__c;
            parent_case.CSAT__c = so.CSAT__c;
            parent_case.CSAT_Survey_Response__c = collatedResponse;
            
            ParentCases.put(parent_case.Id, parent_case);
        } else if (runFromAnswers) {
            so.Collated_Responses__c = collatedResponse;
        }
    }
    
    private string getAnswerCollation(Survey_Answer__c sa, integer indent) {
        string ind0 = string.valueOf((indent - 1) * 40);
        string ind1 = string.valueOf(indent * 40);
        string ind2 = string.valueOf((indent + 1) * 40);
        return ( 
            (sa.Response__c != null && sa.Response__c != '')
             ||
            (sa.Detail_Response__c != null && sa.Detail_Response__c != '')
            ? '<div style="margin-left: ' + ind0 + 'px;"><b>' + sa.Question_Prompt__c + '</b></div>'
            + ( sa.Response__c != null && sa.Response__c != ''
              ? '<div style="margin-left: ' + ind1 + 'px;">' + sa.Response__c + '</div>'
              : ''
              )
            : ''
            )
            +
            ( sa.Detail_Response__c != null && sa.Detail_Response__c != ''
              &&
              sa.Question_Detail_Prompt__c != null && sa.Question_Detail_Prompt__c != ''
            ? '<div style="margin-left: ' + ind1 + 'px;"><b>' + sa.Question_Detail_Prompt__c + '</b></div>'
            + '<div style="margin-left: ' + ind2 + 'px;">' + sa.Detail_Response__c + '</div>'
            : ''
            )
            +
            ( sa.Detail_Response__c != null && sa.Detail_Response__c != ''
              &&
              (sa.Question_Detail_Prompt__c == null || sa.Question_Detail_Prompt__c == '')
            ? '<div style="margin-left: ' + ind1 + 'px;">' + sa.Detail_Response__c + '</div>'
            : ''
            )
            +
            ( sa.Follow_Ups__r.size() > 0
              &&
              sa.Question_Detail_Prompt__c != null && sa.Question_Detail_Prompt__c != ''
            ? '<div style="margin-left: ' + ind1 + 'px;"><b>' + sa.Question_Detail_Prompt__c + '</b></div>'
            : ''
            );
    } 
}