force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Downgrade_Explanation_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Downgrade_Explanation_Prompt__c</fullName>
    <inlineHelpText>The prompt to display to the user when attempting to Downgrade the CSAT (only displayed if &quot;Require Downgrade Explanation&quot; is checked).</inlineHelpText>
    <label>Downgrade Explanation Prompt</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Footnotes__c.field-meta.xml
<CustomField>
    <fullName>Footnotes__c</fullName>
    <label>Footnotes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <inlineHelpText>Externally visible instructions, generally displayed at the top of the survey page.</inlineHelpText>
    <label>Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <inlineHelpText>URL of custom logo for the survey. Used in the event your survey site has a need for a customizable logo (e.g. a client logo, or your own).</inlineHelpText>
    <label>Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Negative_Display__c.field-meta.xml
<CustomField>
    <fullName>Negative_Display__c</fullName>
    <inlineHelpText>What text to display if/when user follows link from &quot;negative&quot; button in email (URL contains csat=Negative parameter)</inlineHelpText>
    <label>Negative Display</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Neutral_Display__c.field-meta.xml
<CustomField>
    <fullName>Neutral_Display__c</fullName>
    <inlineHelpText>What text to display if/when user follows link from &quot;neutral&quot; button in email (URL contains csat=Neutral parameter)</inlineHelpText>
    <label>Neutral Display</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <inlineHelpText>Description of purpose, notes on delivery mechanism and timing, etc.</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Positive_Display__c.field-meta.xml
<CustomField>
    <fullName>Positive_Display__c</fullName>
    <inlineHelpText>What text to display if/when user follows link from &quot;positive&quot; button in email (URL contains csat=Positive parameter)</inlineHelpText>
    <label>Positive Display</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Post_Submission_Display__c.field-meta.xml
<CustomField>
    <fullName>Post_Submission_Display__c</fullName>
    <inlineHelpText>This text is displayed to the survey recipient after they complete the survey.</inlineHelpText>
    <label>Post-Submission Display</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Primary_Color__c</fullName>
    <defaultValue>&quot;rgb(18,142,210)&quot;</defaultValue>
    <inlineHelpText>RGB or Hex color used for subtle styling changes in survey.</inlineHelpText>
    <label>Primary Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Requires_Downgrade_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Requires_Downgrade_Explanation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box to force the respondent to have to answer the &quot;Downgrade Explanation&quot; prompt before the new CSAT is saved.</inlineHelpText>
    <label>Requires Downgrade Explanation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Requires_Upgrade_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Requires_Upgrade_Explanation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box to force the respondent to have to answer the &quot;Upgrade Explanation&quot; prompt before the new CSAT is saved.</inlineHelpText>
    <label>Requires Upgrade Explanation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Survey_Title__c.field-meta.xml
<CustomField>
    <fullName>Survey_Title__c</fullName>
    <inlineHelpText>Externally visible title, generally displayed at the top of the survey page.</inlineHelpText>
    <label>Survey Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Upgrade_Explanation_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Upgrade_Explanation_Prompt__c</fullName>
    <inlineHelpText>The prompt to display to the user when attempting to Upgrade the CSAT (only displayed if &quot;Require Upgrade Explanation&quot; is checked).</inlineHelpText>
    <label>Upgrade Explanation Prompt</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Survey Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Detail_Response__c.field-meta.xml
<CustomField>
    <fullName>Detail_Response__c</fullName>
    <inlineHelpText>Recipient&apos;s response to the request for additional detail.</inlineHelpText>
    <label>Detail Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Question_Detail_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Question_Detail_Prompt__c</fullName>
    <formula>Survey_Question__r.More_Info_Prompt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question Detail Prompt</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Question_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Question_Prompt__c</fullName>
    <formula>Survey_Question__r.Prompt__c</formula>
    <label>Question Prompt</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <inlineHelpText>Recipient&apos;s response to the prompt.</inlineHelpText>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <label>Survey Response</label>
    <referenceTo>Survey_Response__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If the Survey Response is case-specific then this is said case - otherwise this is blank (e.g. for non-support related surveys).</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>The person the survey was sent to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/CSAT__c.field-meta.xml
<CustomField>
    <fullName>CSAT__c</fullName>
    <defaultValue>&quot;Neutral&quot;</defaultValue>
    <label>CSAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Downgrade_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Downgrade_Explanation__c</fullName>
    <inlineHelpText>The response the respondent gave to the &quot;Downgrade Explanation Prompt&quot; (only available &quot;Downgrade Explanation Required&quot; on Survey).</inlineHelpText>
    <label>Downgrade Explanation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The survey this response applies to.</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey_Response_URL__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response_URL__c</fullName>
    <formula>HYPERLINK(
   $Setup.Survey_Settings__c.Survey_Base_URL__c + &quot;?srId=&quot; + CASESAFEID(Id)
  ,
  &quot;Response URL&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Survey Response URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Upgrade_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Upgrade_Explanation__c</fullName>
    <inlineHelpText>The response the respondent gave to the &quot;Upgrade Explanation Prompt&quot; (only available &quot;Upgrade Explanation Required&quot; on Survey).</inlineHelpText>
    <label>Upgrade Explanation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SurveyEmailController.cls
global class SurveyEmailController extends SurveyBase
{
    global SurveyEmailController(ApexPages.StandardController stdC) { }
    
    public Id caseId {get; set;}
    public Id surveyId {get; set;}
    public Id responseId {get; set;}
         
    private Case pvt_surveyCase;     
    public Case surveyCase
    {
        get
        {
            if (caseId == null) { return null; }
            return [SELECT Id, Subject, Description, ContactId
                      FROM Case
                     WHERE Id = :caseId
                     LIMIT 1
                   ];
        }
    }
    
    private Survey__c pvt_survey;     
    public Survey__c survey
    {
        get
        {
            if (surveyId == null) { return null; }
            return [SELECT Notes__c, Logo__c, Primary_Color__c, Survey_Title__c
                         , Downgrade_Explanation_Prompt__c, Upgrade_Explanation_Prompt__c
                         , Requires_Downgrade_Explanation__c, Requires_Upgrade_Explanation__c
                         , Instructions__c, Footnotes__c, Post_Submission_Display__c
                         , Negative_Display__c, Neutral_Display__c, Positive_Display__c
                      FROM Survey__c
                     WHERE Id = :surveyId
                     LIMIT 1
                   ];
        }
    }
    
    private Survey_Response__c pvt_surveyResponse;     
    public Survey_Response__c surveyResponse
    {
        get
        {
            if (responseId == null) { return null; }
            return [SELECT Id, Case__c, Contact__c, Survey__c, CSAT__c
                         , Downgrade_Explanation__c, Upgrade_Explanation__c, Survey_Response_URL__c
                         , Survey__r.Notes__c, Survey__r.Logo__c, Survey__r.Primary_Color__c, Survey__r.Survey_Title__c
                         , Survey__r.Downgrade_Explanation_Prompt__c, Survey__r.Upgrade_Explanation_Prompt__c
                         , Survey__r.Requires_Downgrade_Explanation__c, Survey__r.Requires_Upgrade_Explanation__c
                         , Survey__r.Instructions__c, Survey__r.Footnotes__c, Survey__r.Post_Submission_Display__c
                         , Survey__r.Negative_Display__c, Survey__r.Neutral_Display__c, Survey__r.Positive_Display__c
                         , ( SELECT Id, Question_Type__c, Question_Prompt__c, Response__c
                                  , Question_Detail_Prompt__c, Detail_Response__c
                               FROM Survey_Answers__r
                           )
                      FROM Survey_Response__c
                     WHERE Id = :responseId
                     LIMIT 1
                   ];
        }
    }
    
    public PageReference SendSurvey() { return null; }
    public PageReference ResendSurveyResponse() { return null; }
    public PageReference ResendSurvey() { return null; }
    
    
  /*
  public void SendEmail(Id who, Id what, Id template, Id orgEmail, string subject, string body)
  {
    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
    if (template != null)
    {
        message = Messaging.renderStoredEmailTemplate(template, who, what);
    }
    else
    {
        message.setTargetObjectId(who);
        message.setWhatId(what);
        if (body != '') { message.setHtmlBody(body); }
    }
    if (subject != '') { message.setSubject(subject); }
    
    if (orgEmail != null)
    {
      message.setOrgWideEmailAddressId(orgEmail);
    }
    Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
    Messaging.SendEmailResult[] results = null;
    
    //try
    //{
        results = Messaging.sendEmail(messages);
    //}
    //catch (DMLException e)
    //{
    //    system.debug('Email failed');
    //}

    if (results[0].success)
    {
        System.debug('The email was sent successfully.');
    }
    else
    {
        System.debug('The email failed to send: ' + results[0].errors[0].message);
    }
  }
  */
}